# Generated by Django 4.2.5 on 2023-09-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_rename_data_views_lesson_data_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonwatch',
            name='watch_time',
            field=models.IntegerField(default=0),
        ),
    ]
