# Generated by Django 4.2.5 on 2023-09-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_lessonwatch_data_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='data_viewed',
        ),
    ]
